# Generated by Django 3.1.1 on 2020-09-16 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('url', models.SlugField(max_length=130, unique=True)),
                ('diagonal', models.CharField(max_length=255, verbose_name='Диагональ')),
                ('display_type', models.CharField(max_length=100, verbose_name='Тип дисплея')),
                ('resolution', models.CharField(max_length=100, verbose_name='Разрешение экрана')),
                ('accum_volume', models.CharField(max_length=100, verbose_name='Объем аккумулятора')),
                ('ram', models.CharField(max_length=100, verbose_name='Оперативная память')),
                ('sd', models.BooleanField(default=True)),
                ('sd_volume', models.CharField(max_length=100, verbose_name='Максимальный размер карт памяти')),
                ('main_cam_mp', models.CharField(max_length=100, verbose_name='Основная камера')),
                ('frontal_cam_mp', models.CharField(max_length=100, verbose_name='Фронтальная камера')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Смартфон',
                'verbose_name_plural': 'Смартфоны',
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('url', models.SlugField(max_length=130, unique=True)),
                ('diagonal', models.CharField(max_length=255, verbose_name='Диагональ')),
                ('display_type', models.CharField(max_length=100, verbose_name='Тип дисплея')),
                ('processor_freq', models.CharField(max_length=100, verbose_name='Частота процессора')),
                ('ram', models.CharField(max_length=100, verbose_name='Оперативная память')),
                ('video_card', models.CharField(max_length=255, verbose_name='Видео карта')),
                ('time_without_charge', models.CharField(max_length=100, verbose_name='Время работы от батареи')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Ноутбук',
                'verbose_name_plural': 'Ноутбуки',
            },
        ),
    ]
