# Generated by Django 3.2.9 on 2021-11-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='order',
            field=models.ManyToManyField(null=True, related_name='related_customer', to='store.Order', verbose_name='Заказы покупателя'),
        ),
    ]
