# Generated by Django 3.2.9 on 2021-11-13 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryfeature',
            options={'verbose_name_plural': 'Характеристики категорий'},
        ),
        migrations.AlterModelOptions(
            name='featurevalidator',
            options={'verbose_name_plural': 'Валидные значения'},
        ),
        migrations.AlterModelOptions(
            name='productfeatures',
            options={'verbose_name_plural': 'Характеристики товара'},
        ),
    ]
